framework:
    secret: '%env(APP_SECRET)%'

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    validation:
        enabled: true

    php_errors:
        log: true

    # API Platform serialization
    serializer:
        circular_reference_handler:
            App\Utility\API\CircularReferenceHandlerUtility
        mapping:
            paths: ['%kernel.project_dir%/config/api/serialization']
