imports:
    - {resource: './api/authentication/*.yaml'}
    - {resource: './api/filters/user_management/*.yaml'}

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Action\:
        resource: '../src/Action'
        tags: ['controller.service_arguments']

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Swagger\SwaggerDecorator:
        decorates: 'api_platform.swagger.normalizer.documentation'
        arguments: ['@App\Swagger\SwaggerDecorator.inner']
        autoconfigure: false
